version: '3.8'
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
  cloud-api:
    container_name: cloud-text-searcher-container
    build:
      context: packages/cloud-document-text-search-api
    image: cloud_text_search_api
    depends_on:
      - postgres
      - elasticsearch
      - redis-queue
    ports:
      - 3000:8000
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      ES_PORT: 9200
    links:
      - postgres
    volumes:
      - './:/src'
  redis-queue:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  cloud-scheduler:
    container_name: cloud-document-scheduler-container
    build:
      context: packages/cloud-document-scheduler
    image: cloud_document_scheduler
    depends_on:
      - postgres
      - elasticsearch
      - redis-queue
volumes:
  postgres:
    driver: local
