name: Build Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 16.x, 14.x]
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

